### ISSUE TITLE
Documentation for Chrome on iOS

### ISSUE THREAD

**Issue by danharrelson** [allmarkedup/snoopy#11]
I found that Snoopy works on Chrome for iPad and iPhone. Using bookmarklets is not as intuitive in that browser. Here's the instructions I used: http://www.idownloadblog.com/2012/06/30/how-to-easily-use-bookmarklets-in-google-chrome-for-ios/

I'd be happy to write docs for Chrome if it's part of the git repo.

**Comment by allmarkedup** [comment]
Hi Dan - great to know that it works in Chrome, thanks. And it would be awesome if you fancied adding a bit to the docs about that, they are powered by Github pages so exist in the 'gh-pages' branch of this repo (https://github.com/allmarkedup/snoopy/tree/gh-pages).

Many thanks!!

Mark
