### ISSUE TITLE
Need to check that the DOM is ready

### ISSUE THREAD

**Issue by jbrooksuk** [allmarkedup/snoopy#7]
If you open the Snoopy bookmarklet whilst the page is loading the content, certainly in Google Chrome, you'll receive a:

<pre>Uncaught TypeError: Cannot call method 'appendChild' of undefined</pre>

Because the content has not loaded already.

A check needs to be put into place to wait for the DOM to have loaded before Snoopy opens.

**Comment by allmarkedup** [comment]
Good spot - this definitely needs to go in there, I have seen what you've put into your fork which looks good, although at this time I will probably leave out the scroll test that gives IE support as the rest of the lib is not intended to support IE (and may never be).

**Comment by jbrooksuk** [comment]
Awesome.

Leaving IE out, at least for the time being (until perhaps a "good") IE9 release is made?
